import { Amplify } from 'aws-amplify';

/**
 * Configure Amplify from amplify_outputs.json IF it exists.
 *
 * That file is generated by `npx ampx sandbox` / a deploy and is gitignored, so
 * it's absent on a fresh clone. We use import.meta.glob (which resolves to an
 * empty map when the file is missing, instead of failing the build) so the app
 * runs in "preview mode" — no auth wall — until a backend is provisioned. Once
 * outputs exist, real Cognito auth kicks in automatically.
 */
const modules = import.meta.glob('../amplify_outputs.json', { eager: true }) as Record<
  string,
  { default: unknown }
>;

export let amplifyConfigured = false;

export function configureAmplify(): void {
  const outputs = Object.values(modules)[0]?.default;
  if (outputs) {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    Amplify.configure(outputs as any);
    amplifyConfigured = true;
  }
}
